### ISSUE TITLE
Inertial seperator CAS annunciation

### ISSUE THREAD

**Issue by kaerbr** [guifarias31/msfs_tbm930_project#14]
The inertial seperator is no longer announced in the CAS, even though the effect of the inertial seperator is still there.
v 0.4.15

![grafik](https://user-images.githubusercontent.com/70379879/95079413-e0f8aa80-0716-11eb-82ee-812b26e33784.png)

**Comment by guifarias31** [comment]
This is a know issue since I ajusted how much the inertial separator affects the torque. I decreased the effect from the default 25% to 22%, and the CAS light stopped working.
I thought @withinboredom [had fixed it](https://github.com/guifarias31/msfs_tbm930_project/pull/11) but apparently it's still not working.

**Comment by withinboredom** [comment]
I'm investigating this

**Comment by withinboredom** [comment]
Should be fixed in #17, it was a basic syntax error

**Comment by kaerbr** [comment]
Works now like a charm!
Thanks to @withinboredom with his #17 ❤️
