### ISSUE TITLE
No CAS message for inertial separator

### ISSUE THREAD

**Issue by AndersHogqvist** [guifarias31/msfs_tbm930_project#2]
I'm not sure if this is caused by your mod or if they did something in the latest patch, but the CAS message for inertial separator has disappeared.

If you are able to get it back it would be great if you could add a 30s delay from switching it on to the CAS message showing up. This is from the POH of the TBM930:

CAS message lights on when vanes have reached their maximum deflection and remains visible asl ong as switch remains ON. Full deflection takes about 30 seconds.

**Comment by guifarias31** [comment]
I reduced the inertial separator effect from 25% to 22% decrease in TRQ, and as a result the panel massage doesn't light up, and I could not fix this.
To make the inertial separator act as default and consequently to make the light work, just remove the Deice.xml file and it's line from layout.json. Personaly, I prefer 22% and no lights rather than 25% and lights.
![image](https://user-images.githubusercontent.com/70555403/93717879-ee2a6c80-fb4e-11ea-8f39-dd33558cbde0.png)

**Comment by AndersHogqvist** [comment]
Roger that
